name: Build-OpenWrt-modem-auto-reboot

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        deskripsi: 'Silakan isi nomor versi Rilis (kosongkan untuk tidak dipublikasikan)'
        required: false
        default: ''
      text:
        deskripsi: 'Silakan isi deskripsi rilis'
        required: false
        default: ''
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TAG: "${{ github.event.inputs.tag }}"
  TZ: Asia/Shanghai
permissions:
  contents: write
jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_generic
          - x86_64
        sdk:
          - openwrt-24.10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-modem-auto-reboot
          NO_REFRESH_CHECK: true
          V: s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EasyTier-${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/

      - name: Create compress files
        run: |
          #tar -zcvf EasyTier-${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/ packages_ci
          zip -j EasyTier-${{ matrix.arch }}-${{ matrix.sdk }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*

      - name: Release
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            body: |

             - Di antara mereka, **`openwrt-24.10`** berisi paket instalasi ipk dan **`SNAPSHOT`** berisi paket instalasi apk

             - **`*.apk` adalah versi baru paket OpenWrt APK** Lewati perintah sertifikat untuk paket apk
             `apk add --allow-untrusted luci-app-modem-auto-reboot.apk`

             ${{ github.event.inputs.text }}
           
            tag_name: ${{ env.TAG }}
            files: EasyTier-${{ matrix.arch }}-${{ matrix.sdk }}.zip
 
